---
goscheme:
  build: .
  dockerfile: docker/Dockerfile
  expose:
    - 9000
  ports:
    - 9000:9000
  stdin_open: true
  volumes:
    - ./:/root/go-scheme
  environment:
    - "TZ=Japan"
    - "DISPLAY=docker.for.mac.localhost:0"
  container_name: go-scheme
